import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import { headers } from 'next/headers'
import { CartProvider } from "../context/cart";
import { Car } from "lucide-react";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const pathname = headers().get('x-next-url')
  

  // const headerList = headers();
  // const pathname = headerList.get("x-current-path");

  // const isHomePage = pathname == '/'

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          {children}
        </CartProvider>
        
        <Footer />
      </body>
    </html>
  );
}
