import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import { headers } from 'next/headers'
import { CartProvider } from "../context/cart";
import { RecentsProvider } from "../context/recents";

import { Car } from "lucide-react";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Eldi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <RecentsProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </RecentsProvider>
        
        <Footer />
      </body>
    </html>
  );
}
